---
title: "02 Data Acqusition"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
#1 Working with Spotify API

```{r}
library(lubridate)
library(spotifyr)
library(knitr)
library(tidyverse)
library(ggplot2)


Sys.setenv(SPOTIFY_CLIENT_ID = 'f35cad951d934aa09a2dd473e8a3dd7f')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '2b9ea328c0cc467992f62245e66c5ea3')

access_token <- get_spotify_access_token()
last_played_tbl<-get_my_recently_played(limit = 10) %>% 
  mutate(artist.name = map_chr(track.artists, function(x) x$name[1]),
         played_at = as_datetime(played_at)) %>% 
  select(track.name, artist.name, track.album.name, played_at) %>% 
 # kable() #showstable in console
mutate(artist.name)


last_played_tbl
##last_played_tbl
##track.name    artist.name        track.album.name           played_at
##1   Hans is real      Hans Must            Hans is real 2022-04-26 13:40:26
##2   Young Hearts  Aardvark Lies             Street Life 2022-04-26 13:37:25
##3      La Cuenta      Aguacates                  Verdes 2022-04-26 13:34:57
##4           Same   Bulletkampsh Best Deep House, Vol. 1 2022-04-26 13:32:17
##5 Diamond Pizzle Barefoot Creek               Sunscapes 2022-04-26 13:31:08
##6     Saber Algo      CHAPARREX             Movimientos 2022-04-26 13:27:22
##7   Hans is real      Hans Must            Hans is real 2022-04-26 13:24:27
##8   Hans is real      Hans Must            Hans is real 2022-04-26 13:23:17
##9   Hans is real      Hans Must            Hans is real 2022-04-26 13:22:07


last_played_tbl%>%
ggplot(x=played_at, aes(played_at, track.name, colour = artist.name)) + 
  geom_point()

```
#2 Collecting competitor data from ROSE bikes



  
  # WEBSCRAPING

#1.0 LIBRARIES
```{r}
library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing
library(purrr)
library(unglue)

```
#1.1 COLLECT PRODUCT FAMILIES
```{r}
url_home          <- "https://www.rosebikes.de/fahrr%C3%A4der/gravel"
html_home         <- read_html(url_home)
#xopen(url_home) # Open links directly from RStudio to inspect them

# 01. Get available bike categories
bike_category_tbl <- html_home %>%
  
  # Get the nodes for the families ...
  html_nodes(css = "h4.basic-headline__title") |> #("element is h4 .class")
  html_text() |> 
  as_tibble()
  

bike_price_tbl <- html_home %>%
# Get the nodes for the prices ...
html_nodes(css = ".catalog-category-bikes__price-title") |> #(.class)
  html_text() |>
  as_tibble()

  cleaned<-gsub("[^0.-9,-]","",bike_price_tbl)
  cleaned<-str_remove_all(cleaned,",00")
  
  bike_price_cleaned<-as_tibble(cleaned)
  bike_price_cleaned_s<-bike_price_cleaned%>%separate(col    = value,
                    into   = c("1", "2", "3","4"),
                    sep    = ",") %>%
    t
  
  #bike_price_cleaned_t<-t(bike_price_cleaned_s)
  

bike_data_joined_tbl <- cbind(bike_category_tbl, bike_price_cleaned_s)
colnames(bike_data_joined_tbl)<-c("Bike","Price[€]")
```
```{r}
bike_data_joined_tbl
```