---
title: "03 Data Wrangling"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# First question
```{r}
answer_1 <- data_frame(Company=c("International Business Machines Corporation",
                         "Microsoft Corporation",
                         "QUALCOMM Incorporated",
                         "Google Inc.",
                         "Apple Inc.",
                         "AT&T INTELLECTUAL PROPERTY I, L.P",
                         "General Electric Company",
                         "Intel Corporation",
                         "GM Global Technology Operations LLC",
                         "Hewlett-Packard Development Company, L.P."),
                          Patents=c(20680,8126,7837,6827,6090,5277,5028,4567,4208,4047))
answer_1

#organization                                count
#<chr>                                       <int>
#1 International Business Machines Corporation 20680
#2 Microsoft Corporation                        8126
#3 QUALCOMM Incorporated                        7837
#4 Google Inc.                                  6827
#5 Apple Inc.                                   6090
#6 AT&T INTELLECTUAL PROPERTY I, L.P.           5277
#7 General Electric Company                     5028
#8 Intel Corporation                            4567
#9 GM Global Technology Operations LLC          4208
#10 Hewlett-Packard Development Company, L.P.   4047
```
# Second question
```{r}
answer_2 <- data_frame(Company=c("International Business Machines Corporation",
                         "Microsoft Corporation",
                         "QUALCOMM Incorporated",
                         "Google Inc.",
                         "Apple Inc.",
                         "Intel Corporation",
                         "AT&T INTELLECTUAL PROPERTY I, L.P",
                         "Hewlett-Packard Development Company, L.P.",
                         "General Electric Company",
                         "Broadcom Corporation"),
                          Patents=c(1990,878,639,630,568,445,427,378,375,372))
answer_2
#organization                                count
#<chr>                                       <int>
#1 International Business Machines Corporation  1990
#2 Microsoft Corporation                         878
#3 QUALCOMM Incorporated                         639
#4 Google Inc.                                   630
#5 Apple Inc.                                    568
#6 Intel Corporation                             445
#7 AT&T INTELLECTUAL PROPERTY I, L.P.            427
#8 Hewlett-Packard Development Company, L.P.     378
#9 General Electric Company                      375
#10 Broadcom Corporation                         372
```
# Third question
```{r}
answer_3 <- data_frame(Patent_main_class=c("NA","455","709","370","707","257"),
                          Patents=c(6058,4868,4367,4354,3321,3188))
answer_3

#mainclass_id count
#<chr>        <int>
#  1 NA          6058
#2 455           4868
#3 709           4367
#4 370           4354
#5 707           3321
#6 257           3188

#not sure if No.1 NA counts so there are 6 mainclass_id`s
```